BDS_Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from BDS_Site import settings

urlpatterns = [
    path('admin-loco/', admin.site.urls),
    path('', include('site_bds.urls')),
    path('', include('yourproject.urls')),
    path('', include('site_stats.urls')),
    path('', include('site_gadgetes.urls')),
    path('', include('customer.urls')),
    path('captcha/', include('captcha.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from . import views

app_name = 'customer'


urlpatterns = [
    # Ajout et modif client
    path('add-profil-customer', views.add_profil_customer, name='add_profil_customer'),
    path('edit-profil-customer/<int:customer_id>/', views.edit_profil_customer, name='edit_profil_customer'),   # Ajout et modif client pro
]

templates/site/account.html
{% extends 'base-pages.html' %}
{% load static %}

{% block title %}Mon compte{% endblock %}

{% block content %}
	<section id="hero">
		<svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
		     viewBox="0 24 150 28 " preserveAspectRatio="none">
			<defs>
				<path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
			</defs>
			<g class="wave1">
				<use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
			</g>
			<g class="wave2">
				<use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
			</g>
			<g class="wave3">
				<use xlink:href="#wave-path" x="50" y="9" fill="#fff">
			</g>
		</svg>
	</section><!-- End H -->

	<!-- Start: Contact coordonnées-->
	<div class="container min-vh-100">
		<section id="account" class="account bg-light">
			<div class="text-center py-5">
				<h1 class="title-color">Mon espace client</h1>
				<div class="divider"></div>
			</div>
			<!-- Profile user -->
			<div class="row">
				<!-- colonne 1 -->
				<div class="col-lg-3 col-md-3 col-12 text-center p-2">
					{% if customer.image %}
						<div class="p-2">
							<img src="{{ customer.image.url }}" alt="user"
							     class="rounded-circle bg-white p-2"
							     height="150px">
						</div>
					{% else %}
						<div class="p-2">
							<img src=" {% static "icons/utilisateur-100.png" %}" alt="user"
							     class="rounded-circle bg-white p-2"
							     height="150px">
						</div>
					{% endif %}
					{% if customer.first_name %}
						<h5>Bonjour {{ customer.first_name }}</h5>
					{% else %}
						<h5>Bonjour {{ user.username }} {% if customer.last_name %} {{ customer.last_name }} {{ endif }}

						{% endif %} </h5>
					{% endif %}
					{% if customer and customer.id %}
						<a href="{% url 'customer:edit_profil_customer' customer.id %}">Modifier</a>
					{% else %}
						<a href="{% url 'customer:add_profil_customer' %}" class="text-danger">
							Compléter mon profil
						</a>
					{% endif %}
				</div>
				<!-- colonne 2 -->
				<div class="col-lg-9 md-10 col-12">
					<nav>
						<ul class="nav nav-tabs" role="tablist">
							<!-- Mes informations personnelles -->
							<li class="nav-item" role="presentation">
								<a class="nav-link color-tab-pane" data-bs-toggle="pill" data-bs-target="#tab1"
								   role="tab">
									<i class="bi bi-person-exclamation"
									   data-bs-toggle="tooltip"
									   data-bs-placement="bottom"
									   data-bs-custom-class="custom-tooltip"
									   data-bs-title="Mes informations personnelles">
										Mes informations personnelles
									</i>
								</a>
							</li>
							<!-- Mes Projets -->
							<li class="nav-item" role="presentation">
								<a class="nav-link color-tab-pane" data-bs-toggle="pill" data-bs-target="#tab2" role="tab">
									<i class="bi bi-bag-heart"></i>
									<span class="hidden"
									      data-bs-toggle="tooltip"
									      data-bs-placement="bottom"
									      data-bs-custom-class="custom-tooltip"
									      data-bs-title="Consulter ses projets">
                                        Mes projets
                                    </span>
									{% if unpaid_exists %}
										<span class="badge bg-danger ms-1">!</span>
									{% endif %}
								</a>
							</li>
							<!-- Mes documents -->
							<li class="nav-item" role="presentation">
								<a class="nav-link color-tab-pane" data-bs-toggle="pill" data-bs-target="#tab3" role="tab">
									<i class="bi bi-file-earmark-person-fill"></i>
									<span class="hidden" data-bs-toggle="tooltip"
									      data-bs-placement="bottom"
									      data-bs-custom-class="custom-tooltip"
									      data-bs-title="Affichage de la liste des documents">
										Mes documents
									</span>
								</a>
							</li>
						</ul>
					</nav>
					<div class="tab-content">
						<!-- Mes informations personnelles -->
						<div class="tab-pane fade" id="tab1" role="tabpanel">
							<div class="row">
								<div class="col-12">
									<div class="p-4">
										{% if customer.first_name and customer.last_name %}
											<h5>
												<i class="bi bi-person"></i> {{ customer.first_name }} {{ customer.last_name }}
											</h5>
										{% else %}
											<p><i class="bi bi-person"></i> Nom et prénom : <span class="text-red"> A renseigner</span>
											</p>
										{% endif %}

										{% if customer.address %}
											<p><i class="bi bi-geo"> </i> {{ customer.address }}
												{% if customer.complement_address %},
													{{ customer.complement_address }}<br>
												{% endif %}
												<br>
												<i class="bi bi-house"></i> {{ customer.zip_code }} {{ customer.city }}
											</p>
										{% else %}
											<p>
												<i class="bi bi-geo"> Adresse : </i>
												<span class="text-red"> A renseigner</span>
											</p>
										{% endif %}

										{% if customer.mail %}
											<p>
												<i class="bi bi-envelope-at-fill"></i> {{ customer.mail }}
											</p>
										{% else %}
											<p><i class="bi bi-envelope-at-fill"></i> {{ user.email }}
											<a href="{% url 'account_email' %}">
												<small>(Modifier)</small>
											</a>
										{% endif %}

										{% if customer.phone %}
											<p><i class="bi bi-telephone"></i> {{ customer.phone }}</p>
										{% else %}
											<p><i class="bi bi-telephone"></i> Téléphone : <span class="text-red"> A renseigner</span>
											</p>
										{% endif %}

									</div>
								</div>
							</div>
						</div>
						<!-- Mes projets -->
						<div class="tab-pane fade" id="tab2" role="tabpanel">
							<div class="row">
								<div class="col-12">
									<div>
										<div class="row block-fields d-flex justify-content-between align-items-center mt-3">
											<div style="overflow-x: auto;">
												<table class="table table-bordered table-responsive rounded border overflow-hidden">
													<thead class="thead-light">
													<tr>
														<th scope="col" class="align-middle bg-info">Référence</th>
														<th scope="col" class="align-middle bg-info">Statut</th>
														<th scope="col" class="align-middle bg-info">Nom du Projet</th>
														<th scope="col" class="align-middle bg-info">Domaine</th>
														<th scope="col" class="align-middle bg-info">Serveur</th>
														<th scope="col" class="align-middle bg-info">
															Typo de projet
														</th>
														<th scope="col" class="align-middle bg-info">
															Maintenance
														</th>
													</tr>
													</thead>
													<tbody>
													{% for project in projects %}
														<tr class="align-items-center">
															<td>
																{{ project.ref }} <br>
																<a href="{% url 'details_my_project' project.id %}">
																	<i class="bi bi-eye"> Détail</i>
																</a>
															</td>
															<td>{{ project.status }}</td>
															<td>{{ project.project_name }}</td>
															<td>{{ project.domaine }}</td>
															<td>{{ project.server }}</td>
															<td>{{ project.project_type }}</td>
															<td>{{ project.maintenance_contract }}</td>
														</tr>
													{% empty %}
														<h5 class="text-red">Aucun document pour le moment</h5>
													{% endfor %}
												</table>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!-- Mes documents -->
						<div class="tab-pane fade" id="tab3" role="tabpanel">
							<div class="row">
								<div class="col-lg-12">
									<div>
										test
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="py-5 p-4 text-start">
						{% for message in messages %}
							{% if message.tags == 'error' %}
								<div class="toast align-items-center text-white bg-danger border-0 show"
								     role="alert">
									<div class="d-flex">
										<div class="toast-body">
											{{ message }}
										</div>
										<button type="button" class="btn-close btn-close-white me-2 m-auto"
										        data-bs-dismiss="toast"></button>
									</div>
								</div>
							{% endif %}
						{% endfor %}
						<p class="text-muted">
							(Vous pouvez consulter vos informations en navigant avec les onglets ci-dessus.)
						</p>
					</div>
				</div>
			</div>
		</section>
	</div>
{% endblock %}

templates/site/blog-single.html
{% extends 'base-pages.html' %}
{% load static %}

{% block title %}News{% endblock %}


{% block header %}
	{% include "partials/header.html" %}
{% endblock %}


{% block content %}

	<section id="hero">
    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
      <defs>
        <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
      </defs>
      <g class="wave1">
        <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
      </g>
      <g class="wave2">
        <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
      </g>
      <g class="wave3">
        <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
      </g>
    </svg>

  </section><!-- End Hero -->

    <!-- ======= Blog Section ======= -->
    <section class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
      <div class="container">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry entry-single">
              <div class="d-flex justify-content-center">
                <img src="{{ blogs.image.url }}" alt="{{ blogs.title }}" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog_single' blog_id=blogs.id %}">{{ blogs.title }}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i>
					<a href="{% url 'blog_single' blog_id=blogs.id %}">
						<time datetime="2020-01-01">{{ blogs.created_at }}</time>
					</a>
                </ul>
              </div>

              <div class="entry-content">
	              <div>
		              <p>
	                {{ blogs.text|safe }}
                    </p>
	              </div>
				  <div class="m-5">
                    <img src="{{ blogs.image_2.url }}" alt="{{ blogs.title }}" class="img-fluid">
				  </div>
	              <div>
		              <p>
                        {{ blogs.text_details|safe }}
		              </p>
	              </div>
              </div>

				<div class="m-5">
                    <img src="{{ blogs.image_3.url }}" alt="{{ blogs.title }}" class="img-fluid">
                 </div>
                <p>
                  {{ blogs.text_details_2|safe }}
                </p>
            </article><!-- End blog entry -->
          </div><!-- End blog entries list -->

        <div class="col-lg-4">
			<div class="sidebar">

				<div class="sidebar-item search-form">
					<img src="{% static 'images/54-Grande.jpeg'  %}" alt="Logo-Miguet-Menuiserie"
					     class="rounded" height="200" width="270">
				</div><!-- End sidebar search form-->

				<h3 class="sidebar-title">Toutes les news</h3>
				<div class="sidebar-item recent-posts">
					{% for blog_all in blog_all %}
						<div class="post-item clearfix">
							<img src="{{ blog_all.image.url }}" alt="{{ blog_all.title }}" height="50" width="80">
							<h4><a href="{% url 'news' %}#blog-{{ blog.id }}">{{ blog_all.title }}</a></h4>
							<time datetime="2020-01-01">{{ blog_all.created_at }}</time>
						</div>
					{% endfor %}
				</div>
				<!-- End sidebar recent posts-->

			</div><!-- End sidebar -->

		</div><!-- End blog sidebar -->

        </div><!-- End row -->

      </div><!-- End container -->

    </section><!-- End Blog Section -->

  </main><!-- End #main -->

{% endblock %}

templates/site/contact.html
{% extends "base-pages.html" %}
{% load custom_filter_form %}
{% load static %}

{% block title %}Contact{% endblock %}

{% block content %}
	<section id="hero">
		<svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
		     viewBox="0 24 150 28 " preserveAspectRatio="none">
			<defs>
				<path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
			</defs>
			<g class="wave1">
				<use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
			</g>
			<g class="wave2">
				<use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
			</g>
			<g class="wave3">
				<use xlink:href="#wave-path" x="50" y="9" fill="#fff">
			</g>
		</svg>
	</section><!-- End Hero -->
	<!-- ======= Contact Section ======= -->
	<section id="contact" class="contact">
		<div class="container">

			<div class="section-title" data-aos="fade-up">
				<h1 class="title-index fs-2">Contactez-nous, BDS <small>(Bélier Développement Solution)</small><br>
					Développeur de sites web, applications et de toutes solutions numériques</h1>
			</div>
			<div class="section-title" data-aos="fade-up">
				<h2>Contact</h2>
				<p>Contact</p>
			</div>

			<div class="row">

				<div class="col-lg-4" data-aos="fade-right" data-aos-delay="100">
					<div class="info">
						<div class="address">
							<a href="https://maps.app.goo.gl/aQHpGfwvEvhobLkX7"><i
									class="icofont-google-map"></i></a>
							<h4>Localité</h4>
							<p>38490 AOSTE</p>
						</div>

						<div class="email">
							<a href="mailto:contact.bds38.com"><i class="icofont-envelope"></i></a>
							<h4>Email</h4>
							<p>contact@bds38.com</p>
						</div>

						<div class="phone">
							<a href="tel:+33673212272"><i class="icofont-phone"></i></a>
							<h4>Téléphone</h4>
							<p>06 73 21 22 72</p>
						</div>
					</div>

				</div>

				<div class="col-lg-8 mt-5 mt-lg-0" data-aos="fade-left" data-aos-delay="200">
					{% if messages %}
						<div>
							{% include "components/messages.html" with messages=messages %}
						</div>
					{% endif %}
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="form-row">
							<div class="col-12 ">
								<div class="form-group">
									<label for="name">Nom</label>
									{{ form.name }}
									{% if form.name.errors %}
										{% for error in form.name.errors %}
											<span>
				                                {{ error }}
				                            </span>
										{% endfor %}
									{% endif %}
								</div>
								<div class="form-group">
									<label for="email">Email</label>
									{{ form.email }}
									{% if form.email.errors %}
										{% for error in form.email.errors %}
											<span>
                                                {{ error }}
                                            </span>
										{% endfor %}
									{% endif %}
								</div>
								<div class="form-group">
									<label for="subject">Sujet</label>
									{{ form.subject }}
									{% if form.subject.errors %}
										{% for error in form.subject.errors %}
											<span>
                                                {{ error }}
                                            </span>
										{% endfor %}
									{% endif %}
								</div>
								<div class="form-group">
									<label for="message">Message</label>
									{{ form.message }}
									{% if form.message.errors %}
										{% for error in form.message.errors %}
											<span>
                                                {{ error }}
                                            </span>
										{% endfor %}
									{% endif %}
								</div>
								<div class="form-group">
									{% if form.captcha.errors %}
										{% for error in form.captcha.errors %}
											<span class="text-danger">{{ error }}</span>
										{% endfor %}
									{% endif %}
									<label for="captcha">{{ form.captcha }} <br>Code de Vérification (Saisir le code de validation) </label>

								</div>

								<div class="php-email-form">
									<div class="text-center">
										<button class="btn btn-general" type="submit">
											Envoyer
										</button>
									</div>
								</div>

							</div>
							<div class="mb-3">{{ popup_form.honeypot }}</div>
					</form>
				</div>
			</div>
		</div>
	</section><!-- End Contact Section -->
{% endblock content %}

templates/site/details-my-project.html
{% extends 'base-pages.html' %}
{% load static %}

{% block title %}Mon compte{% endblock %}

{% block content %}
 <section id="hero">
			<svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
			     viewBox="0 24 150 28 " preserveAspectRatio="none">
				<defs>
					<path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
				</defs>
				<g class="wave1">
					<use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
				</g>
				<g class="wave2">
					<use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
				</g>
				<g class="wave3">
					<use xlink:href="#wave-path" x="50" y="9" fill="#fff">
				</g>
			</svg>
		</section>
	<!-- header -->
	<div class="container min-vh-100">
		<!-- End header -->
		<section id="account" class="account bg-light p-2">
			<div class="text-center mt-4">
				<h1 class="title-color">Mon installation {{ project.project_name }} </h1>
				<div class="divider"></div>
			</div>
			<div class="row d-flex justify-content-center align-items-center mt-5">
				<div class="col-lg-6 col-md-6 col-sm-12">
					<div class="container-description-installation mt-5">
						<h2>{{ project.project_name }}</h2>
						<hr>
						<div class="mt-2">
							<h5><strong>Reférence : </strong>{{ project.ref }}</h5>
							<h5><strong>Statut : </strong>{{ project.status }}</h5>
							<h5><strong>Nom du projet : </strong>{{ project.project_name }}</h5>
							<h5><strong>Type de projet : </strong>{{ project.project_type}}</h5>
							<h5><strong>Domaine : </strong>{{ project.domaine }}</h5>
							<h5><strong>Serveur : </strong>{{ project.server }}</h5>
							<h5><strong>Maintenance : </strong>{{ project.maintenance_contract }}</h5>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>

	<!-- End détails installations -->


{% endblock %}

templates/site/gallery-single.html
{% extends 'base-pages.html' %}
{% load static %}

{% block title %}Gallerie{% endblock %}


{% block header %}
	{% include "partials/header.html" %}
{% endblock %}


{% block content %}

	<section id="hero">
    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
      <defs>
        <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
      </defs>
      <g class="wave1">
        <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
      </g>
      <g class="wave2">
        <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
      </g>
      <g class="wave3">
        <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
      </g>
    </svg>

  </section><!-- End Hero -->

    <!-- ======= Blog Section ======= -->
    <section class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
      <div class="container">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry entry-single">
	            <div>
		            <h1>{{ gallery.name }}</h1>
	            </div>
              <div class="d-flex justify-content-center">
                <img src="{{ gallery.image.url }}" alt="{{ gallery.title }}" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{% url 'gallery_single' gallery_id=gallery.id %}">{{ gallery.title }}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i>
					<a href="{% url 'gallery_single' gallery_id=gallery.id %}">
						<time datetime="2020-01-01">{{ gallery.created_at }}</time>
					</a>
                </ul>
              </div>

              <div class="entry-content">
	              <div>
		              <p>
	                {{ gallery.description|safe }}
                    </p>
	              </div>
              </div>
            </article><!-- End blog entry -->
          </div><!-- End blog entries list -->

        <div class="col-lg-4">
			<div class="sidebar">

				<div class="sidebar-item search-form">
					<img src="{% static 'images/54-Grande.jpeg'  %}" alt="Logo-Miguet-Menuiserie"
					     class="rounded" height="200" width="270">
				</div><!-- End sidebar search form-->

				<h3 class="sidebar-title">Toutes les commandes</h3>
				<div class="sidebar-item recent-posts">
					{% for gallery_all in gallery_all %}
						<div class="post-item clearfix">
							<img src="{{ gallery_all.image.url }}" alt="{{ gallery_all.title }}" height="50" width="80">
							<h4><a href="{% url 'gallery_single' gallery_id=gallery_all.id %}">{{ gallery_all.name }}</a></h4>
							<time datetime="2020-01-01">{{ gallery.created_at }}</time>
						</div>
					{% endfor %}
				</div>
				<!-- End sidebar recent posts-->

			</div><!-- End sidebar -->

		</div><!-- End blog sidebar -->

        </div><!-- End row -->

      </div><!-- End container -->

    </section><!-- End Blog Section -->

  </main><!-- End #main -->

{% endblock %}

templates/site/news.html
{% extends "base-pages.html" %}
{% load static %}

{% block title %}News{% endblock %}

{% block content %}
	<section id="hero">
		<svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
		     viewBox="0 24 150 28 " preserveAspectRatio="none">
			<defs>
				<path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
			</defs>
			<g class="wave1">
				<use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
			</g>
			<g class="wave2">
				<use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
			</g>
			<g class="wave3">
				<use xlink:href="#wave-path" x="50" y="9" fill="#fff">
			</g>
		</svg>

	</section><!-- End Hero -->

	<!-- ======= Blog Section ======= -->
	<section class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					{% for blogs in blogs %}
						{% if blogs.en_ligne %}
							<article class="entry" id="blog-{{ blogs.id }}">

								<h2 class="entry-title">
									<a href="{% url 'blog_single' blog_id=blogs.id %}">{{ blogs.title }}</a>
								</h2>

								<div class="entry-meta">
									<ul>
										<li class="d-flex align-items-center">
											<i class="icofont-wall-clock"></i>
											<a href="{% url 'blog_single' blog_id=blogs.id %}">
												<time datetime="2020-01-01">{{ blogs.created_at }}</time>
											</a>
									</ul>
								</div>
								<div class="d-flex justify-content-center">
									<img src="{{ blogs.image.url }}" alt="{{ blogs.title }}"
									     class="img-fluid rounded mb-1"
									>
								</div>
								<div class="entry-content mt-3">
									<p>
										{{ blogs.text|safe }}
									</p>
									<div class="read-more">
										<a class="btn-get-started" style="border-radius: 30px" href="{% url 'blog_single' blog_id=blogs.id %}">Voir plus</a>
									</div>
								</div>

							</article><!-- End blog entry -->
						{% endif %}

					{% endfor %}
				</div><!-- End blog entries list -->

				<div class="col-lg-4">
					<div class="sidebar">
						<div class="sidebar-item">
							<img src="{% static 'images/54-Grande.jpeg' %}" alt="image-judoAdministrator"
							     class="rounded" height="200" width="270">
						</div>

						<h3 class="sidebar-title">Toutes les news</h3>
						<div class="sidebar-item recent-posts">
							{% for blog in blogs %}
								{% if blog.en_ligne %}
									<div class="post-item clearfix">
										<img src="{{ blog.image.url }}" alt="{{ blog.title }}">
										<h4><a href="#blog-{{ blog.id }}">{{ blog.title }}</a></h4>
										<time datetime="2020-01-01">{{ blog.created_at }}</time>
									</div>
								{% endif %}

							{% endfor %}
						</div><!-- End sidebar recent posts-->
					</div><!-- End sidebar -->
				</div><!-- End blog sidebar -->
			</div><!-- End .row -->
		</div><!-- End .container -->
	</section><!-- End Blog Section -->

	</main><!-- End #main -->

{% endblock content %}

templates/site/page-success-client.html
{% extends "base-pages.html" %}
{% load static %}

{% block title %}Connexion{% endblock %}

{% block content %}
	<section id="hero">
    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
      <defs>
        <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
      </defs>
      <g class="wave1">
        <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
      </g>
      <g class="wave2">
        <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
      </g>
      <g class="wave3">
        <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
      </g>
    </svg>

  </section><!-- End Hero -->
		<div class="mask d-flex align-items-center h-100 gradient-custom-3 py-5">
			<div class="container-fluid h-100 overflow-auto">
				<div class="row d-flex justify-content-center align-items-center h-100">
					<div class="col-12 col-md-9 col-lg-7 col-xl-6">
						<div class="card" style="border-radius: 15px">
							<div class="card-header">
								<h2 class="text-uppercase text-center mt-3" style="color: black">
									Message enregistré
								</h2>
								<hr />
								<div class="card-body text-center">
									<p>Le message est bien enregistré {{ contact.name }}, nous reviendrons vers vous très rapidement.</p>
									<p>Merci pour votre confiance.</p>
								</div>
								<div class="card-footer text-center">
								<a href="{% url 'index'%}" class="btn-general">
										Continuer
								</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock content %}